"""EU AI Act Art. 50(2) provenance marking for generated content.

Providers of generative AI systems must mark outputs as artificially generated
in a machine-readable format (Regulation (EU) 2024/1689, Art. 50(2), applicable
from 2026-08-02). For a JSON text API the practical machine-readable layer is
response metadata: a top-level ``provenance`` object injected into
non-streaming generative bodies, plus an ``X-AI-Generated`` header on every
generative response. SSE streams get the HEADER ONLY: injecting synthetic
events breaks strict SDK stream parsers, and rewriting the terminal chunk would
sit inside the billing moat (streaming.drain), so stream-body marking is
deferred.

Errors, /v1/models and /v1/embeddings are not generated content and are never
marked; /v1/audio/transcriptions gets the header only (the transcript's
semantics come from the input audio -- the Art. 50(2) no-substantial-alteration
carve-out). ``[provenance] enabled = false`` is the SIGHUP-reloadable kill
switch for an emergency rollback if a client's strict parser rejects the extra
field.

A future stream-body marking (v2) belongs in a WRITE-side transform inside
streaming.drain(), between ``on_chunk`` and ``write_block`` -- never on the
read/accumulate side, which must keep feeding usage accumulators verbatim even
after a client disconnect.
"""

import datetime
import decimal
import json
import logging
import math

from . import __version__


HEADER = "X-AI-Generated"
FIELD = "provenance"

# IPTC digital source type for content fully generated by a trained model --
# the controlled vocabulary C2PA, OpenAI and Meta already use for marking, so
# downstream tooling gets a recognized term instead of a bespoke label.
DIGITAL_SOURCE_TYPE = ("http://cv.iptc.org/newscodes/digitalsourcetype/"
    "trainedAlgorithmicMedia")
LEGAL_BASIS = "Regulation (EU) 2024/1689, Article 50(2)"
DEFAULT_GENERATOR = "comtegra-llmproxy"


def enabled(cfg):
    return cfg.get("provenance", {}).get("enabled", True)


def headers(cfg):
    """Marking headers for a generative response; {} when disabled.

    Streaming handlers must pass these into stream_through(): the header
    middlewares skip prepared responses, so a header added there would never
    reach a stream (the same reason stream_through sets X-Request-ID itself).
    """
    if not enabled(cfg):
        return {}
    return {HEADER: "true"}


def build(cfg, model_id, request_id):
    """The provenance object injected into non-streaming bodies.

    ``model_id`` is the PUBLIC backend alias the client selected (b_name),
    never the upstream model path; ``request_id`` ties the marking to the
    billing rows and logs for traceability. Kept a pure flat dict: a future
    signing layer (JWS) attaches a signature alongside these claims without
    touching the handlers.
    """
    return {
        "ai_generated": True,
        "digital_source_type": DIGITAL_SOURCE_TYPE,
        "legal_basis": LEGAL_BASIS,
        "generator": cfg.get("provenance", {}).get("generator",
            DEFAULT_GENERATOR),
        "generator_version": __version__,
        "model_id": model_id,
        "request_id": str(request_id),
        "timestamp": datetime.datetime.now(datetime.UTC)
            .strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


def _default(value):
    """json.dumps default for the Decimals produced by parse_float=Decimal.

    float() rounds each Decimal to the nearest double -- the same value any
    standard JSON client parses from the original bytes -- and json emits the
    shortest round-tripping repr, so re-serialization is numerically lossless
    for double-precision consumers.
    """
    if isinstance(value, decimal.Decimal):
        f = float(value)
        if math.isinf(f) and value.is_finite():
            # A finite literal beyond double range (e.g. 1e400) would
            # serialize as a bare Infinity -- invalid JSON. Signal mark() to
            # fall back to the upstream bytes instead of corrupting the body.
            raise OverflowError("JSON number out of double range")
        return f
    raise TypeError("Object of type %s is not JSON serializable"
        % type(value).__name__)


def mark(cfg, body, data, model_id, request_id):
    """Mark one parsed non-streaming generative response.

    Returns ``(body_bytes, extra_headers)``: ``data`` (the parsed ``body``)
    with a top-level ``provenance`` object injected -- mutated in place, but
    only a top-level key is added, so the caller's later ``usage`` extraction
    is unaffected -- re-serialized; or the untouched upstream ``body`` and {}
    when disabled. An upstream top-level ``provenance`` key would be REPLACED
    (no supported backend emits one; the proxy's marking is authoritative).
    """
    hdrs = headers(cfg)
    if not hdrs:
        return body, {}
    data[FIELD] = build(cfg, model_id, request_id)
    try:
        try:
            # ensure_ascii=False + compact separators keep the bytes close to
            # what vLLM/FastAPI emit (raw UTF-8, compact) instead of
            # \u-escaping every non-ASCII character.
            marked = json.dumps(data, ensure_ascii=False,
                separators=(",", ":"), default=_default).encode("utf-8")
        except UnicodeEncodeError:
            # A lone surrogate (e.g. a generation truncated by max_tokens in
            # the middle of an emoji, passed through by an ASCII-escaping
            # backend) survives json.loads but is not UTF-8-encodable.
            # Re-escape instead: still valid JSON, the client gets the
            # surrogate escaped exactly as the upstream sent it -- and a
            # billable 200 never becomes an unbilled 500 here.
            logging.warning("Lone surrogate in %s response; re-serialized "
                "with ASCII escapes (request_id=%s)", model_id, request_id)
            marked = json.dumps(data, ensure_ascii=True,
                separators=(",", ":"), default=_default).encode("utf-8")
    except OverflowError:
        # _default: a finite number beyond double range cannot be re-emitted
        # as valid JSON. Unreachable from real LLM payloads; forward the
        # upstream bytes and keep the header layer of the marking.
        logging.warning("Number out of double range in %s response; "
            "forwarding unmarked body (request_id=%s)", model_id, request_id)
        data.pop(FIELD, None)
        return body, hdrs
    return marked, hdrs
